### ISSUE TITLE
posenet using tflite

### ISSUE THREAD

**Issue by ctippur** [google-coral/tflite#35]
Hello,

I am interested in using posenet to extract points of reference. 
I followed the methodology described [Here](https://medium.com/roonyx/pose-estimation-and-matching-with-tensorflow-lite-posenet-model-ea2e9249abbd).
I took a video of myself as being stationary. The reference points I got seem to be quite dynamic (contrary to my hypothesis).
For example, the nose and the eyes seem to have moved in both horizontal and vertical planes.

Wondering if you can give some pointers to improve the accuracy. As an initial test, I have a 30 FPS video with me being stationary for 10 seconds and I would like to see the generated coordinates without much variation.

Thanks,
S

**Comment by Namburger** [comment]
@ctippur Thanks for reaching out! 
The issues seems to be caused by the model's accuracy, which wont be modifiable since it's already in tflite format. 
We actually have a similar project here which proven results and is targeted for edgetpu platform if you want to check it out instead?
https://github.com/google-coral/project-posenet

**Comment by manoj7410** [comment]
Is this still an issue for you ?

**Comment by manoj7410** [comment]
Marking it as closed due to lack of activity. Feel free to reopen if this issue still persists.
